### 5. Assign respective topic number to each document

In [1]:
import pandas as pd
import time

start_time = time.time()

In [2]:
topic_prob = pd.read_csv('document_topic_matrix.csv')

In [3]:
topic_prob.head()

   Unnamed: 0    0         1         2         3         4         5
0           0  0.0  0.686263  0.000000  0.000000  0.304112  0.000000
1           1  0.0  0.000000  0.176718  0.815826  0.000000  0.000000
2           2  0.0  0.034871  0.085443  0.147316  0.729608  0.000000
3           3  0.0  0.014044  0.000000  0.373295  0.560586  0.047742
4           4  0.0  0.000000  0.000000  0.920776  0.074596  0.000000

In [4]:
topic_prob = topic_prob.iloc[: , 1:]
topic_prob.head()

     0         1         2         3         4         5
0  0.0  0.686263  0.000000  0.000000  0.304112  0.000000
1  0.0  0.000000  0.176718  0.815826  0.000000  0.000000
2  0.0  0.034871  0.085443  0.147316  0.729608  0.000000
3  0.0  0.014044  0.000000  0.373295  0.560586  0.047742
4  0.0  0.000000  0.000000  0.920776  0.074596  0.000000

In [5]:
for i in range(6):
    name = 'Topic ' + str(i+1)
    topic_prob.rename(columns={topic_prob.columns[i]: name},inplace=True)
topic_prob.head()

   Topic 1   Topic 2   Topic 3   Topic 4   Topic 5   Topic 6
0      0.0  0.686263  0.000000  0.000000  0.304112  0.000000
1      0.0  0.000000  0.176718  0.815826  0.000000  0.000000
2      0.0  0.034871  0.085443  0.147316  0.729608  0.000000
3      0.0  0.014044  0.000000  0.373295  0.560586  0.047742
4      0.0  0.000000  0.000000  0.920776  0.074596  0.000000

In [6]:
df = pd.read_csv('cord19_vaccine_2020_dataset_withBi-Trigram.csv')

In [7]:
selected_topic = []
max_percent = []

In [8]:
for idx in range(len(topic_prob)):
    for col in topic_prob.columns:
        if(topic_prob.loc[idx,col] == max(topic_prob.iloc[idx])):
            selected_topic.append(col)
            max_percent.append(max(topic_prob.iloc[idx]))

In [9]:
topic_prob['Selected Topic'] = selected_topic
topic_prob['Max Percentage'] = max_percent

In [10]:
topic_prob.head()

,Topic 1,Topic 2,Topic 3,Topic 4,Topic 5,Topic 6,Selected Topic,Max Percentage
0,0.0,0.686263,0.000000,0.000000,0.304112,0.000000,Topic 2,0.686263
1,0.0,0.000000,0.176718,0.815826,0.000000,0.000000,Topic 4,0.815826
2,0.0,0.034871,0.085443,0.147316,0.729608,0.000000,Topic 5,0.729608
3,0.0,0.014044,0.000000,0.373295,0.560586,0.047742,Topic 5,0.560586
4,0.0,0.000000,0.000000,0.920776,0.074596,0.000000,Topic 4,0.920776

In [11]:
df['Selected Topic'] = selected_topic

In [12]:
df.to_csv('dataset_with_topic.csv')

In [13]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,title,abstract,publish_time,abstract_tokens,Lemma_Tokens,Phrase_Lemma_Tokens,Phrase_Lemma_Tokens_trigram,Selected Topic
0,4,4,4246,Synthetic carbohydrate-based vaccines: challen...,glycoconjugate vaccines based on bacterial cap...,2020-01-03,"['glycoconjugate', 'vaccines', 'based', 'bacte...","['glycoconjugate', 'vaccine', 'base', 'bacteri...","['glycoconjugate', 'vaccine', 'base', 'bacteri...","['glycoconjugate', 'vaccine', 'base', 'bacteri...",Topic 2
1,393220,483203,736911,Retinal Hemorrhage after SARS-CoV-2 Vaccination,to report retinal vein occlusion (rvo) and age...,2021-12-05,"['report', 'retinal', 'vein', 'occlusion', 'rv...","['report', 'retinal', 'vein', 'occlusion', 'rv...","['report', 'retinal_vein', 'occlusion', 'rvo',...","['report', 'retinal_vein', 'occlusion', 'rvo',...",Topic 4
2,6,6,4248,Identification of antigens presented by MHC fo...,mycobacterium tuberculosis (m.tb) is responsib...,2020-01-03,"['mycobacterium', 'tuberculosis', 'responsible...","['mycobacterium', 'tuberculosis', 'responsible...","['mycobacterium_tuberculosis', 'responsible', ...","['mycobacterium_tuberculosis', 'responsible', ...",Topic 5
3,393222,483205,736914,Next-Generation Serology by Mass Spectrometry:...,[image: see text] methods of antibody detectio...,2021-12-08,"['image', 'see', 'text', 'methods', 'antibody'...","['image', 'see', 'text', 'method', 'antibody',...","['image_see', 'text', 'method', 'antibody', 'd...","['image_see_text', 'method', 'antibody', 'dete...",Topic 5
4,262152,302536,481315,Pre-vaccination Antibody Titers Against Season...,background the prospective assessment of sars-...,2021,"['background', 'prospective', 'assessment', 's...","['background', 'prospective', 'assessment', 's...","['background', 'prospective', 'assessment', 's...","['background', 'prospective', 'assessment', 's...",Topic 4
...,...,...,...,...,...,...,...,...,...,...,...
30203,262119,302494,481255,Twitter discourse reveals geographical and tem...,the speed at which social media is propagating...,2021,"['speed', 'social', 'media', 'propagating', 'm...","['speed', 'social', 'medium', 'propagating', '...","['speed', 'social_medium', 'propagating', 'mis...","['speed', 'social_medium', 'propagating', 'mis...",Topic 1
30204,262124,302500,481267,[SARS-CoV-2 and sodium transport: a diabolical...,the covid 19 pandemic remains a serious public...,2020,"['covid', 'pandemic', 'remains', 'serious', 'p...","['covid', 'pandemic', 'remain', 'serious', 'pu...","['covid', 'pandemic', 'remain', 'serious', 'pu...","['covid', 'pandemic', 'remain', 'serious_publi...",Topic 2
30205,393203,483178,736874,Meta-analysis of transcriptomes of SARS-Cov2 i...,the covid-19 pandemic resulting from the sever...,2020-05-12,"['pandemic', 'resulting', 'severe', 'acute', '...","['pandemic', 'result', 'severe', 'acute', 'res...","['pandemic', 'result', 'severe_acute', 'respir...","['pandemic', 'result', 'severe_acute_respirato...",Topic 5
30206,131067,131715,226612,"Disinformation, vaccines, and covid-19. Analys...",introduction: the debate on the covid-19 vacci...,2021,"['introduction', 'debate', 'vaccines', 'presen...","['introduction', 'debate', 'vaccine', 'present...","['introduction', 'debate', 'vaccine', 'present...","['introduction', 'debate', 'vaccine', 'present...",Topic 1
30207,393214,483196,736901,Revisiting the role of pulsed electric fields ...,gene therapies are revolutionizing medicine by...,2021-11-06,"['gene', 'therapies', 'revolutionizing', 'medi...","['gene', 'therapy', 'revolutionize', 'medicine...","['gene', 'therapy', 'revolutionize', 'medicine...","['gene_therapy', 'revolutionize', 'medicine', ...",Topic 5

In [14]:
end_time = time.time()

print('Estimate runtime: ', (end_time-start_time)/60, ' minutes.')

Estimate runtime:  0.9267201503117879  minutes.

In [15]:
import winsound
duration = 1000  # milliseconds
freq = 440  # Hz
    
winsound.Beep(freq, duration)