### 2.3. Add word_id to each entity

In [ ]:
import pandas as pd
import time

start_time = time.time()

In [ ]:
df = pd.read_csv('corpus_with_tags_explodeNeed_version.csv')
df.head()

,Unnamed: 0,Unnamed: 0.1,doc_id,sent_id,text,start,end,type,Unnamed: 0.1.1,index,text_list,word_count,flag,word_id
0,0,0,0,0,angiotensin_converting_enzyme 2,0.0,2.0,GENE_OR_GENOME,0.0,0.0,"['angiotensin_converting_enzyme', '2']",2.0,"['B-GENE_OR_GENOME', 'I-GENE_OR_GENOME']","[0, 1]"
1,1,1,0,0,ace2,3.0,4.0,GENE_OR_GENOME,1.0,0.0,['ace2'],1.0,['B-GENE_OR_GENOME'],[3]
2,2,2,0,0,sars_cov_2,7.0,8.0,CORONAVIRUS,2.0,0.0,['sars_cov_2'],1.0,['B-CORONAVIRUS'],[7]
3,3,3,0,0,receptor,8.0,9.0,CHEMICAL,3.0,0.0,['receptor'],1.0,['B-CHEMICAL'],[8]
4,4,4,0,0,sars_cov_2,13.0,14.0,CORONAVIRUS,4.0,0.0,['sars_cov_2'],1.0,['B-CORONAVIRUS'],[13]

In [ ]:
df['text_list'] = df['text_list'].apply(lambda x: x.strip('][').split(', '))

In [ ]:
df['flag'] = df['flag'].apply(lambda x: x.strip('][').split(', '))

In [ ]:
df['word_id'] = df['word_id'].apply(lambda x: x.strip('][').split(', '))

In [ ]:
df_explode = df.explode(['text_list', 'flag', 'word_id'])

In [ ]:
df_explode.to_csv('corpus_with_tags_all.csv')

In [ ]:
df_explode

,Unnamed: 0,Unnamed: 0.1,doc_id,sent_id,text,start,end,type,Unnamed: 0.1.1,index,text_list,word_count,flag,word_id
0,0,0,0,0,angiotensin_converting_enzyme 2,0.0,2.0,GENE_OR_GENOME,0.0,0.0,'angiotensin_converting_enzyme',2.0,'B-GENE_OR_GENOME',0
0,0,0,0,0,angiotensin_converting_enzyme 2,0.0,2.0,GENE_OR_GENOME,0.0,0.0,'2',2.0,'I-GENE_OR_GENOME',1
1,1,1,0,0,ace2,3.0,4.0,GENE_OR_GENOME,1.0,0.0,'ace2',1.0,'B-GENE_OR_GENOME',3
2,2,2,0,0,sars_cov_2,7.0,8.0,CORONAVIRUS,2.0,0.0,'sars_cov_2',1.0,'B-CORONAVIRUS',7
3,3,3,0,0,receptor,8.0,9.0,CHEMICAL,3.0,0.0,'receptor',1.0,'B-CHEMICAL',8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10388053,10388643,689498,29499,66,"figures_s1 s5 ) , so we advise caution in inte...",21.0,32.0,CHEMICAL,150.0,66.0,'advise',11.0,'I-CHEMICAL',27
10388053,10388643,689498,29499,66,"figures_s1 s5 ) , so we advise caution in inte...",21.0,32.0,CHEMICAL,150.0,66.0,'caution',11.0,'I-CHEMICAL',28
10388053,10388643,689498,29499,66,"figures_s1 s5 ) , so we advise caution in inte...",21.0,32.0,CHEMICAL,150.0,66.0,'in',11.0,'I-CHEMICAL',29
10388053,10388643,689498,29499,66,"figures_s1 s5 ) , so we advise caution in inte...",21.0,32.0,CHEMICAL,150.0,66.0,'interpreting',11.0,'I-CHEMICAL',30
10388053,10388643,689498,29499,66,"figures_s1 s5 ) , so we advise caution in inte...",21.0,32.0,CHEMICAL,150.0,66.0,'this',11.0,'I-CHEMICAL',31

In [ ]:
end_time = time.time()

print('Estimate runtime: ', (end_time-start_time)/60, ' minutes.')

Estimate runtime:  2.936017111937205  minutes.

In [ ]:
# utilized RAM = 9.85 GB, Disk = 41.17 GB