### 3. Merge result from full sentence (1) and ner data (2).

In [ ]:
import pandas as pd
import numpy as np
import json
import time

start_time = time.time()

In [ ]:
df_1 = pd.read_csv('corpus_without_tag_all.csv')
df_1.head()

,Unnamed: 0,doc_id,sent_id,sent_tokens,word_id,tag,Unnamed: 0.1
0,0,0,0,angiotensin_converting_enzyme,0,O,0.0
1,1,0,0,2,1,O,0.0
2,2,0,0,(,2,O,0.0
3,3,0,0,ace2,3,O,0.0
4,4,0,0,),4,O,0.0

In [ ]:
df_2 = pd.read_csv('corpus_with_tags_all.csv')
df_2.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,doc_id,sent_id,text,start,end,type,Unnamed: 0.1.1.1,index,text_list,word_count,flag,word_id
0,0,0,0,0,0,angiotensin_converting_enzyme 2,0.0,2.0,GENE_OR_GENOME,0.0,0.0,'angiotensin_converting_enzyme',2.0,'B-GENE_OR_GENOME',0
1,0,0,0,0,0,angiotensin_converting_enzyme 2,0.0,2.0,GENE_OR_GENOME,0.0,0.0,'2',2.0,'I-GENE_OR_GENOME',1
2,1,1,1,0,0,ace2,3.0,4.0,GENE_OR_GENOME,1.0,0.0,'ace2',1.0,'B-GENE_OR_GENOME',3
3,2,2,2,0,0,sars_cov_2,7.0,8.0,CORONAVIRUS,2.0,0.0,'sars_cov_2',1.0,'B-CORONAVIRUS',7
4,3,3,3,0,0,receptor,8.0,9.0,CHEMICAL,3.0,0.0,'receptor',1.0,'B-CHEMICAL',8

In [ ]:
# df_2['word_id']=df_2['word_id'].astype(int)

In [ ]:
df = pd.merge(df_1, df_2, how = 'left', on=['doc_id', 'sent_id', 'word_id'])

In [ ]:
df.to_csv('corpus_for_ner.csv')

In [ ]:
end_time = time.time()

print('Estimate runtime: ', (end_time-start_time)/60, ' minutes.')

Estimate runtime:  9.502469913164775  minutes.